Add unit tests
nitishragu12/Capstone-Project pull request #132
Opened 2024-10-06 06:26 UTC by ziqichen55555

This pull request introduces unit tests for the PaperMate API, enhancing the overall test coverage of the application. The tests focus on the following aspects:
Mutation Tests: Validates the functionality of data mutations within the API, ensuring that the expected changes occur in the database.
Paper List Tests: Confirms the correct retrieval and processing of paper data, validating that the API endpoints return accurate information.
Search Functionality Tests: Tests the search features to ensure that queries yield expected results and handle edge cases properly.
These tests will help maintain the integrity of the application and catch potential issues early in the development process.
This PR is linked to issue [Test Suites #116](https://github.com/nitishragu12/Capstone-Project/issues/116).

2024-10-06 11:18 UTC, somni1oquist commented on docker-compose.yml
What's the necessity for this secret?

2024-10-06 12:58 UTC, ziqichen55555 commented on api/tests/test_mutation.py
> +        self.assertEqual(paper.doi, "10.37934/araset.48.1.137151")  # Make sure the inserted data is as expected
I got difficulty here😓

2024-10-06 13:06 UTC, somni1oquist commented on api/tests/test_mutation.py
> +        self.assertEqual(paper.doi, "10.37934/araset.48.1.137151")  # Make sure the inserted data is as expected
Then add dummy code and label `# @TODO: assert mutation after request` for this PR's purpose.

2024-10-06 14:10 UTC, maxtse25 commented on api/tests/__init__.py
Instead of overwriting, mock out specific components when necessary

2024-10-06 14:23 UTC, maxtse25 commented on api/tests/test_paper_list.py
I asked ChatGPT and it says `In your case, if performance isn’t a concern and you prefer test isolation (which is generally a good practice), switching to setUp and tearDown instance methods could be a better alternative.` lol

2024-10-10 06:00 UTC, somni1oquist requested changes
Please add coverage to .gitignore and recover docker-compose file

2024-10-11 04:46 UTC, somni1oquist approved these changes
Thanks for all the works!

2024-10-11 04:46 UTC, merged